#!/bin/bash

# Initialize a variable to store the new tag (if found)
new_tag=""

# Get the list of all local Git tags
all_tags=$(git tag -l)

# Get the list of tags associated with the current HEAD
tags_in_head=$(git for-each-ref --format "%(refname:short)" refs/tags --contains HEAD)

# Iterate through all local tags and check if they are in HEAD
for tag in $all_tags; do
    if [[ "$tags_in_head" != *"$tag"* ]]; then
        new_tag="$tag"
        echo "New local tag found: $new_tag"
    fi
done

# Check if a new tag was not found and take action
if [ ! -n "$new_tag" ] && [ "$(git branch --show-current)" == 'main' ]; then
    pnpm publish

    PACKAGE_VERSION=$(cat package.json | grep \\\"version\\\" | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]')

    git tag v$PACKAGE_VERSION

    git push --tag
fi
