#!/bin/bash

set -e  # Exit the script if any command fails

# Initialize a variable to store the new tag (if found)
new_tag=""

# Get the list of all local Git tags
all_tags=$(git tag -l)

# Get the list of tags associated with the current HEAD
tags_in_head=$(git for-each-ref --format "%(refname:short)" refs/tags --contains HEAD)

# Iterate through all local tags and check if they are in HEAD
for tag in $all_tags; do
    if [[ "$tags_in_head" != *"$tag"* ]]; then
        new_tag="$tag"
    fi
done

# Check if a new tag was not found and take action
if [ -n "$new_tag" ]; then
    echo "post-commit 1"
fi

if  [ -z "$(git status --porcelain)" ]; then
    echo "post-commit 2"
fi

if [ "$(git branch --show-current)" == 'main' ]; then
    echo "post-commit 3"
fi

if [ -n "$new_tag" ] && [ -z "$(git status --porcelain)" ] && [ "$(git branch --show-current)" == 'main' ]; then
    npm publish --access=public

    git push && git push --tag
fi
