#!/bin/bash

set -e  # Exit the script if any command fails

# Initialize a variable to store the new tag (if found)
new_tag=""

# Get the list of all local Git tags
all_tags=$(git tag -l)

# Get the list of tags associated with the current HEAD
tags_in_head=$(git for-each-ref --format "%(refname:short)" refs/tags --contains HEAD)

# Iterate through all local tags and check if they are in HEAD
for tag in $all_tags; do
    if [[ "$tags_in_head" != *"$tag"* ]]; then
        new_tag="$tag"
        echo "New local tag found: $new_tag"
    fi
done

# Check if a new tag was not found and take action
if [ ! -n "$new_tag" ]; then
    echo "1"
fi

if [ ! -z "$(git status --porcelain)" ]; then
    echo "2"
fi

if [ ! -n "$new_tag" ] && [ ! -z "$(git status --porcelain)" ]; then
    pnpm link --dir ./node_modules/@eslint

    pnpm lint

    git stash -q --keep-index

    npm --no-git-tag-version version patch

    git stash pop 

    git add package.json
else
    echo "There are uncommitted changes in the repository"
fi
