#!/bin/bash

set -e  # Exit the script if any command fails

if [ ! -z "$(git status --porcelain)" ]; then
    pnpm link --dir ./node_modules/@eslint

    pnpm lint

    git stash -q --keep-index

    npm --no-git-tag-version version patch

    git stash pop 

    git add package.json
else
    echo "There are uncommitted changes in the repository."
fi
